vabold/Kinoko

source/abstract/Archive.cc

Fix ArchiveHandler ctor segfault

---

configure.py

The only downside I can see here is that even if you have just barely started working on a new source file (and it's in an incomplete state) it will (attempt to) be compiled.

Remove hardcoded source file paths

---

source/game/system/map/MapdataStageInfo.cc
source/game/system/map/MapdataStartPoint.cc

closes #86 
thx vabold for the help <3

Fix byteswap map section header count

---

source/game/kart/KartMove.cc
source/game/kart/KartMove.hh
source/game/kart/KartState.cc
source/game/kart/KartState.hh
source/game/system/KPadController.cc
source/game/system/KPadController.hh
testCases.json

TODO;
- Figure out how to get rid of the `goto` in `KartMove::calcRotation()`

Standstill Mini-Turbo Infrastructure

---

STATUS.md
source/game/kart/KartMove.cc
source/game/kart/KartMove.hh
testCases.json

Syncs the RR NG RTA WR moonjump until the boost ramp.

Implement outward drifting

---

source/game/item/KartItem.cc
source/game/kart/KartJump.cc

Thanks to @KooShnoo for identifying the `KartItem` UB.

Fix two sources of undefined behavior

---

STATUS.md
source/game/kart/KartMove.cc
source/game/kart/KartMove.hh
testCases.json

This syncs the RR NG RTA WR until the wavy road section by implementing super mini-turbos.

Sync Super Mini-Turbos

---

source/game/kart/KartMove.cc

Fix cannon parameterIdx overflow

---

.github/workflows/build.yml
.gitignore
STATUS.md
tools/generate_tests.py
tools/status_check.py

Note: Build action must be re-run in the event any other changes are merged to main.
These changes add a build action step which validates that all framecounts in STATUS.md remain up-to-date and accurate. This allows us to better catch instances where changes for one test case help improve the sync of other test cases.

Validate STATUS.md via automation step

---

STATUS.md
source/game/kart/CollisionGroup.cc
source/game/kart/CollisionGroup.hh
source/game/kart/KartCollide.cc
source/game/kart/KartSub.cc
source/game/kart/KartSub.hh

This was originally part of #117 but was found to be not directly related to HWG itself. This seems to pertain to wall clips.

Side collision

---

STATUS.md
source/game/kart/KartMove.cc
source/game/kart/KartMove.hh
source/game/render/KartModel.cc

this syncs outward drifting bikes.

Outward-drifting bikes

---

source/game/field/ObjectDirector.cc
source/game/field/ObjectDirector.hh
source/game/field/ObjectFlowTable.cc
source/game/field/ObjectFlowTable.hh

This is a necessary step before ObjectCollidable implementation.

Add ObjFlow.bin support

---

STATUS.md
source/game/field/KCollisionTypes.hh
source/game/kart/KartCollide.cc
source/game/kart/KartMove.cc
source/game/kart/KartMove.hh
source/game/kart/KartObjectProxy.cc
source/game/kart/KartObjectProxy.hh
source/game/kart/KartReject.cc
source/game/kart/KartReject.hh
source/game/kart/KartState.cc
source/game/kart/KartState.hh
source/game/kart/KartSub.cc

This syncs reject road, specifically focusing on Maple Treeway's half-pipes.

Sync reject road and half-pipes

---

source/game/system/CourseMap.cc
source/game/system/CourseMap.hh
source/game/system/map/MapdataCheckPath.cc
source/game/system/map/MapdataCheckPath.hh
source/game/system/map/MapdataCheckPoint.cc
source/game/system/map/MapdataCheckPoint.hh

Fully implements initialization for `MapdataCheckPath` and `MapdataCheckPoint`.

Initialize checkpoints and checkpaths

---

STATUS.md
source/game/kart/KartHalfPipe.cc
source/game/kart/KartHalfPipe.hh
source/game/kart/KartMove.cc
source/game/kart/KartMove.hh
source/game/kart/KartObjectProxy.cc
source/game/kart/KartObjectProxy.hh
source/game/kart/KartState.cc
source/game/kart/KartState.hh

The scope of this PR is non-trick landing boost from zippers.

Sync zipper landing boosts

---

STATUS.md
source/game/kart/KartCollide.cc
source/game/kart/KartCollide.hh
source/game/kart/KartState.cc

Trigger respawn when falling below y = 0

---

source/game/system/CourseMap.cc
source/game/system/CourseMap.hh
source/game/system/map/MapdataJugemPoint.cc
source/game/system/map/MapdataJugemPoint.hh

Adds infrastructure for loading in the respawn points along a track.

Add JugemPoint infrastructure

---

source/game/kart/KartMove.cc

Once respawn functionality is implemented, this fix will allow rSGB to sync.

Fix ODB lean rotation increment

---

source/game/kart/KartCollide.cc
source/game/kart/KartCollide.hh

Once respawn physics are implemented, these changes will allow the KC ultra TAS to sync the respawn triggers on laps 2 and 3.

Sync solid OOB triggers

---

source/game/kart/KartState.cc

This was causing the MT TAS to desync.

Fix soft wall clip normal

---

.gitignore
tools/discord/bot.py

Currently, this generates KRKGs with a given RKG.
RKG validation through Kinoko is dependent on timers.

Create a Discord bot

---

source/game/scene/RaceScene.cc
source/game/system/CourseMap.cc
source/game/system/CourseMap.hh
source/game/system/RaceManager.cc
source/game/system/RaceManager.hh
source/game/system/map/MapdataCheckPath.cc
source/game/system/map/MapdataCheckPath.hh
source/game/system/map/MapdataCheckPoint.cc
source/game/system/map/MapdataCheckPoint.hh

This is a continuation of checkpoint infrastructure, with the goal of tracking the player's current checkpoint.
The branch is quite messy with many unrelated changes that need to be cleaned up atm.

Implement checkpoint calculation

---

source/game/field/ObjectCollisionCylinder.cc
source/game/kart/KartSub.cc

Also fixes incorrect multVector calls found by @vabold

Fix incorrect boundingRadius check

---

STATUS.md
source/game/field/ObjectDirector.cc
source/game/field/obj/ObjectId.hh

Mario Circuit's trees are just `ObjectCollidable`.

Implement Castletree1c

---

STATUS.md
source/game/field/ObjectDirector.cc
source/game/field/obj/ObjectId.hh

Implement DKtreeA64c

---

source/game/system/CourseMap.cc
source/game/system/CourseMap.hh
source/game/system/map/MapdataPointInfo.cc
source/game/system/map/MapdataPointInfo.hh

This is the first of a few infra requirements for route-based objects (such as Goombas and MH cars)

Implement MapdataPointInfo

---

source/game/field/obj/ObjectCollidable.cc
source/game/field/obj/ObjectCollidable.hh
source/game/field/obj/ObjectDokan.cc
source/game/field/obj/ObjectDokan.hh
source/game/field/obj/ObjectOilSFC.cc
source/game/field/obj/ObjectOilSFC.hh
source/game/kart/KartAction.cc
source/game/kart/KartAction.hh
source/game/kart/KartCollide.cc
source/game/kart/KartCollide.hh
source/game/kart/KartHalfPipe.cc
source/game/kart/KartJump.cc
source/game/kart/KartMove.cc
source/game/kart/KartMove.hh
source/game/kart/KartObjectProxy.cc
source/game/kart/KartObjectProxy.hh
source/game/kart/KartPhysics.cc
source/game/kart/KartPhysics.hh
source/game/kart/KartReject.cc
source/game/kart/KartState.cc
source/game/kart/KartState.hh
source/game/kart/KartSub.cc
source/game/kart/KartSub.hh
source/game/kart/KartSuspensionPhysics.cc
testCases.json

Begin solving rMC3

---

source/game/kart/KartState.cc

This was bothering me so here's a PR

Remove state() getters in KartState

---

source/egg/core/BitFlag.hh
source/game/field/BoxColManager.cc
source/game/field/BoxColManager.hh
source/game/field/CollisionDirector.cc
source/game/field/ObjectDirector.cc
source/game/field/ObjectDrivableDirector.cc
source/game/field/ObjectDrivableDirector.hh
source/game/field/obj/ObjectDrivable.cc
source/game/field/obj/ObjectDrivable.hh

Also made `ObjectDrivable::getCollisionRadius` inline.

Implement ObjectDrivableDirector

---

STATUS.md
source/game/field/CollisionDirector.hh
source/game/field/ObjectDirector.cc
source/game/field/obj/ObjectAurora.cc
source/game/field/obj/ObjectAurora.hh
source/game/field/obj/ObjectId.hh
source/game/field/obj/ObjectRegistry.hh
source/game/system/RaceManager.hh

This syncs the wavy road on Rainbow Road.
Its collision is a quadratic chirp function (fancy way of saying sin function with changing frequency). It's offset by 30 seconds (which actually means that it starts off with frequency 1.25 which then drops to 1 at 30 seconds mid-race, then rises to a maximum of 4 after around 2 mins 13s.
I laid it on pretty heavy with the `constexpr`s so let me know if you want me to remove some of them.

Sync ObjectAurora (RR wavy road)

---

source/game/system/GhostFile.cc
source/game/system/GhostFile.hh
source/host/KReplaySystem.cc

This is the last thing we need to fix for 0.3 release.

Fix malformed ghost file size constant

---

source/abstract/g3d/AnmObj.cc
source/abstract/g3d/AnmObj.hh
source/abstract/g3d/LICENSE
source/abstract/g3d/ResAnmChr.hh
source/abstract/g3d/ResCommon.hh
source/abstract/g3d/ResDic.cc
source/abstract/g3d/ResDic.hh
source/abstract/g3d/ResFile.hh

This adds infra we will need to observe object animation durations.

Add AnmObjChrRes

---

testCases.json

Since RR has been fully synced, the test case should be completing the entire race

Fix RR test case frame count

---

source/game/field/BoxColManager.cc

Fixes a comparison that was swapped causing it to assign incorrect low points and 2 while loops were skipping an iteration.

Fixes in BoxColManager

---

source/host/KReplaySystem.cc

We really need to sort out the system heap at some point.
Closes #311.

Fix replay system panics

---

source/game/kart/KartMove.cc

This syncs the rWS ultra 3lap TAS.

Add HalfPipe invisible wall collision check

---

source/game/field/ObjectDirector.cc
source/game/field/obj/ObjectId.hh
source/game/field/obj/ObjectRegistry.hh
source/game/field/obj/ObjectSandcone.cc
source/game/field/obj/ObjectSandcone.hh

Implement Sandcone

---

STATUS.md
source/game/field/ObjectDirector.cc
source/game/field/obj/ObjectBelt.cc
source/game/field/obj/ObjectBelt.hh
source/game/field/obj/ObjectBeltCrossing.cc
source/game/field/obj/ObjectBeltCrossing.hh
source/game/field/obj/ObjectId.hh
source/game/field/obj/ObjectRegistry.hh

This implements the first set of conveyer belts on Toad's Factory.

Implement ObjectBeltCrossing and ObjectBelt

---

STATUS.md
source/game/field/ObjectDirector.cc
source/game/field/obj/ObjectBeltEasy.cc
source/game/field/obj/ObjectBeltEasy.hh
source/game/field/obj/ObjectId.hh
source/game/field/obj/ObjectRegistry.hh

This syncs the TF conveyers outside of the factory.

Implement ObjectBeltEasy

---

STATUS.md
source/game/field/ObjectDirector.cc
source/game/field/obj/ObjectBreakable.hh
source/game/field/obj/ObjectId.hh
source/game/field/obj/ObjectRegistry.hh
source/game/field/obj/ObjectWoodbox.hh
source/game/field/obj/ObjectWoodboxW.cc
source/game/field/obj/ObjectWoodboxW.hh
source/game/field/obj/ObjectWoodboxWSub.cc
source/game/field/obj/ObjectWoodboxWSub.hh

This syncs the TF box spawner.

Implement ObjectWoodboxW

---

.github/workflows/build.yml
README.md
source/host/Option.cc
source/host/main.cc
tools/discord/bot.py
tools/status_check.py

This fixes #330. Run as:
`./kinoko test -s testCases.bin`
`./kinoko replay -g ghostFile.rkg`

Remove need for -m flag

---

STATUS.md
source/game/field/ObjectDirector.cc
source/game/field/obj/ObjectId.hh
source/game/field/obj/ObjectRegistry.hh
source/game/field/obj/ObjectTwistedWay.cc
source/game/field/obj/ObjectTwistedWay.hh

This syncs the wavy road on BCwii.

Implement TwistedWay

---

STATUS.md
source/game/field/ObjectDirector.cc
source/game/field/obj/ObjectEscalator.cc
source/game/field/obj/ObjectEscalator.hh
source/game/field/obj/ObjectEscalatorGroup.cc
source/game/field/obj/ObjectEscalatorGroup.hh
source/game/field/obj/ObjectId.hh
source/game/field/obj/ObjectRegistry.hh

This syncs the escalators on Coconut Mall.

Implement ObjEscalator and ObjEscalatorGroup

---

source/game/field/RailInterpolator.hh
source/game/field/obj/ObjectBase.hh
source/game/field/obj/ObjectProjectile.hh
source/game/field/obj/ObjectProjectileLauncher.hh
source/game/field/obj/ObjectSniper.cc
source/game/field/obj/ObjectSniper.hh

This is the first phase of changes required to implement the FireSnakes on rDH.

Implement ObjectProjectile, ObjectProjectileLauncher, and ObjectSniper
