vabold/Kinoko

- source/abstract/Archive.cc
- source/game/kart/KartParam.cc
- source/game/kart/KartParam.hh
- source/game/kart/KartParamFileManager.cc
- source/game/kart/KartParamFileManager.hh
- source/game/system/ResourceManager.cc
- source/game/system/ResourceManager.hh
These changes allow for parsing of BSP files. In the process, we also found that the file lookup logic would not navigate through sub-directories.
> Add BSP reading and fix file traversal logic

- source/egg/math/Math.cc
- source/egg/math/Math.hh
- source/egg/math/Quat.cc
- source/egg/math/Quat.hh
- source/egg/math/Vector.cc
- source/egg/math/Vector.hh
- source/game/kart/KartDynamics.cc
- source/game/kart/KartDynamics.hh
- source/game/kart/KartMove.cc
- source/game/kart/KartMove.hh
- source/game/kart/KartObject.cc
- source/game/kart/KartObject.hh
- source/game/kart/KartObjectManager.cc
- source/game/kart/KartObjectProxy.cc
- source/game/kart/KartObjectProxy.hh
- source/game/kart/KartPhysics.cc
- source/game/kart/KartPhysics.hh
- source/game/kart/KartState.cc
- source/game/kart/KartState.hh
- source/game/kart/KartSub.cc
- source/game/kart/KartSub.hh
- source/game/scene/RaceScene.cc
- source/game/system/RaceManager.cc
- source/game/system/RaceManager.hh
This matches the expected values of `KartDynamics::m_pos` and `KartDynamics::m_fullRot` after the call to `KartObject::calcSub`. Only variables which are dependent on the synchronization of these two variables have been implemented.
Further additions in the functions added in this PR may be required in order to sync the second pass.
> Sync frame 0.5

- source/egg/math/Vector.cc
- source/egg/math/Vector.hh
- source/game/kart/KartDynamics.cc
- source/game/kart/KartDynamics.hh
- source/game/kart/KartMove.cc
- source/game/kart/KartMove.hh
- source/game/kart/KartObjectProxy.cc
- source/game/kart/KartObjectProxy.hh
- source/game/kart/KartSub.cc
- source/test/TestDirector.cc
- `KartDynamics::m_totalForce` was not being reset at the end of `KartDynamics::calc`
- `KartDynamics::m_extVel` was not being modified (effectively reset) in `KartSub::calcPass0`
> Sync frame 2

- source/host/System.cc
- source/test/TestDirector.cc
- source/test/TestDirector.hh
Due to the `do-while` loop in `KSystem::run`, a frame would be computed before checking to see if it is within the number of frames we want to simulate, defined by `TARGET_FRAME`.
Note that I've also changed `TestDirector::m_currentFrame` to effectively become 1-indexed. If we want to keep it 0-indexed, then we should change the frame comparison in `calc()` to `++m_currentFrame >= TARGET_FRAME`
> Fix TestDirector framecount off-by-one

- .github/workflows/build.yml
- README.md
- include/Common.hh
- source/test/TestDirector.cc
Shows the hex representation of floats in the DESYNC output. Also avoid imprecise printing of the numeric representation by using `%g` instead of `%f`.
I created a helper function since we will likely have to perform this operation very often for debugging.
> Add hex representation of floats in DESYNC output

- source/egg/math/Matrix.cc
- source/egg/math/Matrix.hh
- source/game/kart/KartDynamics.cc
- source/game/kart/KartObjectProxy.cc
- source/game/kart/KartPhysics.cc
Adds support for overloading `operator[]` with different number of arguments. This requires `C++23` but we are already configured to require that.
See: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2128r6.pdf
> Implement multidimensional subscript operator

- source/egg/math/Matrix.cc
- source/game/field/CollisionDirector.cc
- source/game/kart/KartBody.cc
- source/game/kart/KartBody.hh
- source/game/kart/KartCollide.cc
- source/game/kart/KartDynamics.cc
- source/game/kart/KartDynamics.hh
- source/game/kart/KartMove.cc
- source/game/kart/KartMove.hh
- source/game/kart/KartObject.cc
- source/game/kart/KartObject.hh
- source/game/kart/KartObjectManager.cc
- source/game/kart/KartObjectProxy.cc
- source/game/kart/KartObjectProxy.hh
- source/game/kart/KartState.cc
- source/game/kart/KartState.hh
- source/game/kart/KartSub.cc
- source/game/kart/KartSuspensionPhysics.cc
- source/game/render/KartModel.cc
- source/game/render/KartModel.hh
- source/game/system/KPadController.cc
- testCases.json
This syncs Luke's rMC3 RTA WR ghost until the first shroom, at frame 1425.
- Fixes an off-by-one error in `Matrix34f::multVector` by adding parentheses
- Fix an issue in `findClosestCollisionEntry` where we were iterating the entire array. This could lead to accessing uninitialized/old entries that are no longer valid.
- Implemented `PlayerModel`, as it sets `KartBody::m_anAngle` which is used when computing the wheel matrix.
- Implemented offroad slowdown factor
- Fixed `KartState::m_bStickRight` and `m_bStickLeft` being inverted
> Sync drifting and quick hops

- source/game/field/CourseColMgr.cc
- source/game/field/KColData.cc
- source/game/field/KColData.hh
Right now (and by right now I mean in a future PR where we sync rBC), we make use of three sphere collision check functions. They are 95% the same, differing only by certain if-statements based on the TYPE of check performed (at least colliding with an edge, colliding beyond the edge, and colliding while moving towards).
The functions are ugly in Ghidra. Keeping them separate in Kinoko does not make debugging any easier (from a LOT of experience). I will argue that conjoining them here helps readability, as we can distinguish between what types of checks are being performed on a given collision check.
> Clean up KCL collision functions

- source/test/TestDirector.hh
The message for `f32` specialization of `TestDirector::checkDesync` still had `Frame: XXXX` even though we got rid of it since the `Test Case Failed` string already shows the framecount.
> Remove redundant/non-standard desync print formatting

- source/game/kart/KartBody.cc
- source/game/kart/KartBody.hh
- source/game/kart/KartObject.cc
- source/game/kart/KartParam.cc
- source/game/kart/KartParam.hh
closes #89
I'm not quite sure what a "Vehicle-relative bike" is, or if the Quacker is the only one.
I also don't know what to name the new test cases, please advise. for now:
```
[TestDirector.cc:112] Test Case Passed: Grumble Volcano 15s Ultra Shortcut [411 / 1336]
[TestDirector.cc:112] Test Case Passed: Mushroom Gorge 19s Ultra Shortcut [546 / 1596]
```
whereas main only syncs three frames for each.
I don't know for sure what the next desyncs are, but i can guess. GV is prolly the rock, desync shows velocity dropping to 0 in base, but not in kinoko. MG is probably the mushroom. the eh, _kinoko_, one could say.
I'm also not super sure how the `KartBodyQuacker` ctor and dtor are supposed to look. I'm not super familiar with inheritance.
> Quacker: add `KartBodyQuacker`

- source/game/kart/CollisionGroup.cc
- source/game/kart/CollisionGroup.hh
- source/game/kart/KartCollide.cc
- source/game/kart/KartCollide.hh
- source/game/kart/KartDynamics.cc
- source/game/kart/KartDynamics.hh
- source/game/kart/KartMove.cc
- source/game/kart/KartMove.hh
- source/game/kart/KartObjectProxy.cc
- source/game/kart/KartObjectProxy.hh
- source/game/kart/KartState.cc
- source/game/kart/KartState.hh
- source/game/kart/KartSub.cc
- source/game/kart/KartSuspensionPhysics.cc
- testCases.json
Adds basic functionality of wall bonks.
Contingent on the merging of #83 and #95
> Wall collision infrastructure

- source/game/kart/KartMove.cc
Fixes #91 
FP associativity was causing a slight desync at the start of Koopa Cape. We were also failing to initialize `KartMove::m_up` which would desync the next frame on Koopa Cape.
> Initialize KartMove::m_up and fix FP associativity desync

- source/game/kart/KartCollide.cc
- source/game/kart/KartDynamics.cc
- source/game/kart/KartMove.cc
use [structured binding](https://en.cppreference.com/w/cpp/language/structured_binding) to use two separate variables instead of one `std::pair`. as mentioned, this greatly improves readability.
closes #102
> destructure all `std::pair`

- STATUS.md
- source/egg/math/Matrix.cc
- source/game/kart/KartBody.cc
- source/game/kart/KartDynamics.cc
- source/game/kart/KartDynamics.hh
- source/game/kart/KartMove.cc
- source/game/kart/KartMove.hh
- source/game/kart/KartObject.cc
- source/game/kart/KartObject.hh
- source/game/kart/KartObjectProxy.cc
- source/game/kart/KartObjectProxy.hh
- source/game/kart/KartSuspension.cc
- source/game/kart/KartSuspension.hh
- source/game/kart/KartSuspensionPhysics.cc
- source/game/kart/KartSuspensionPhysics.hh
- source/game/kart/KartTire.cc
- source/game/kart/KartTire.hh
- source/game/render/KartModel.cc
- testCases.json
Thanks to @KooShnoo for a lot of the initial work for this branch!
Fixed #90 
This syncs the first 452 frames of the only kart RTA world record. Specifically the following issues had to be addressed to make this possible:
- In `Matrix34f::inverseTo33`, FP associativity caused off-by-one inaccuracies that eventually led to incorrect rotation.
- Implements `wheelMatrix()` for karts
- Implements `KartDynamics::stabilize()` base class vfunc which is used by karts
- Fixed incorrect `multVector` call in `KartDynamics::calc` (this didn't cause a desync, but for posterity's sake I want to fix it now)
- Added missing `EGG::Mathf::abs()` call in `KartDynamics::calc` (no desync, just posterity's sake)
- Implement KartMoveSub284 renamed as `DriftingParameters` to avoid using hard-coded values that no …
> Kart turn params and rotation

- STATUS.md
- source/game/kart/KartCollide.cc
- source/game/kart/KartCollide.hh
- source/game/kart/KartMove.cc
- source/game/kart/KartMove.hh
- testCases.json
Blocked by #98 #107 and #109
This syncs the RR NG RTA WR (kart) until the SMT.
> Sync outward boost ramp drifts

- include/Common.hh
- source/egg/math/Vector.cc
- source/egg/math/Vector.hh
- source/game/kart/KartParam.cc
- source/game/kart/KartParamFileManager.cc
- source/game/system/map/MapdataAccessorBase.hh
clangd the c/cpp LSP suggested these changes to me. these changes should also enable Kinoko to be built with clang.
clang doesn't support flexible length arrays in the same way gcc does, so i had to add a spurious arbitrary length to  params array in `ParamFile`.
> synchronize with clang

- STATUS.md
- source/game/kart/KartJump.cc
- source/game/kart/KartMove.cc
I accidentally typo'd the trick parameter array. Also moving water is treated as sticky road. This snippet from Tockdom is relevant, in regards to sticky road:
> A type of road that attaches players to the road if they are within 200 units of the road with a correction of up to 200 units/frame. Moving water shares this code internally. The game logic does not care if player is also colliding with a different surface; as long as the player within 200 units of a surface with this attribute, the player's position will be corrected. This effect does not stack; layering on moving water will not make it more intense. The variant controls the terrain type.
> Fix AngleProperties typo and treat moving water as sticky road

- STATUS.md
- source/game/kart/CollisionGroup.cc
- source/game/kart/CollisionGroup.hh
- source/game/kart/KartBody.cc
- source/game/kart/KartBody.hh
- source/game/kart/KartCollide.cc
- source/game/kart/KartCollide.hh
- source/game/kart/KartSub.cc
- source/game/kart/KartSuspensionPhysics.cc
`KartBody` stores our current `sinkDepth` and a `targetSinkDepth` such that when we bounce onto KCL having sink depth property, our hitbox's height is offset gradually.
> Sink bounce

- STATUS.md
- source/game/kart/KartMove.cc
Dependent on #123 
This synchronizes a few extra frames on the rBC ultra test case, where Logan clips up onto the soft wall at the start of the race to prep for the ultra setup.
> Sync soft wall clips

- source/egg/core/Decomp.cc
SZS headers specify the size of the uncompressed data, but there's no validation to make sure the header isn't lying...
> Prevent SZS buffer overruns

- STATUS.md
- source/game/kart/KartMove.cc
This syncs the WGM glitch 3lap RTA WR. There was a missing check to restrict y speed to 90.0f in `KartMove::calcAcceleration`.
> Fix terminal velocity in calcAcceleration

- source/game/field/Object.cc
- source/game/field/Object.hh
- source/game/field/ObjectDirector.cc
- source/game/field/ObjectId.hh
Additions to the blacklist will be one line when we need them. The blacklist can be separated into two categories: ones where collision is disabled in TTs, and the others where there is no collision.
> Add object blacklist

- STATUS.md
- source/game/kart/KartDynamics.cc
- source/game/kart/KartDynamics.hh
- source/game/kart/KartMove.cc
- source/game/kart/KartMove.hh
- source/game/kart/KartState.cc
- source/game/kart/KartSub.cc
Dependent on #120 #126 and #127
Adds a missing setter for `KartDynamics::m_forceUpright`.
During debugging, I also observed a missing `softWallCount` check in `KartState::calcCollisions`, so I've decided to add that in this PR given the sufficiently small scope, and the fact it's closely associated.
> Barrel roll

- STATUS.md
- source/game/kart/KartMove.cc
- source/game/kart/KartMove.hh
This syncs the wall bonk on rDKJP NG by cancelling our drift due to the wall bonk.
> Sync drift cancel due to wall bonk

- STATUS.md
- source/game/kart/KartState.cc
This adds some missing bitfield clearing in `KartState::calc`
> Reset additional KartState bits on KartState::calc call

- include/Common.hh
- source/abstract/memory/ExpHeap.cc
- source/abstract/memory/ExpHeap.hh
- source/abstract/memory/HeapCommon.cc
- source/abstract/memory/HeapCommon.hh
- source/abstract/memory/List.cc
- source/abstract/memory/List.hh
- source/abstract/memory/Memory.hh
- source/egg/core/BitFlag.hh
- source/egg/core/ExpHeap.cc
- source/egg/core/ExpHeap.hh
- source/egg/core/Heap.cc
- source/egg/core/Heap.hh
- source/host/System.cc
Function addresses still need to be added, but the heaps are in a usable state. Closes #2.
> Implement EGG::Heap

- source/game/field/KColData.cc
- source/game/field/KColData.hh
Closes #161.
This results in an approximately 30% speedup on my machine.
I got rid of `m_prismCount` since it isn't used anymore outside of preloading.
I also made sure that in `checkCollision` we retrieve the prisms and normals as references.
> Prism preload

- source/game/system/KPadController.cc
- source/game/system/KPadController.hh
- source/game/system/KPadDirector.cc
- source/game/system/KPadDirector.hh
- source/game/system/RaceConfig.cc
- source/game/system/RaceConfig.hh
- source/host/System.cc
- source/test/TestDirector.cc
- source/test/TestDirector.hh
This removes a dependency on the host system from RaceConfig, allowing external applications to interface with Kinoko in a much simpler way.
Closes #157.
> Add support for host controllers

- source/egg/math/Vector.cc
- source/egg/math/Vector.hh
- source/game/system/CourseMap.cc
- source/game/system/CourseMap.hh
- source/game/system/map/MapdataCheckPath.cc
- source/game/system/map/MapdataCheckPath.hh
- source/game/system/map/MapdataCheckPoint.cc
- source/game/system/map/MapdataCheckPoint.hh
Adds `MapdataCheckPoint` and `MapdataCheckPath`, but not the rest of the checkpoint infrastructure like all the sector functions.
This is the first PR towards syncing respawn positions, verifying lap completion, and calculating lap times and finish times.
Makes progress towards #20.
> Add Checkpoints

- source/game/item/KartItem.cc
- source/game/kart/KartBurnout.cc
- source/game/kart/KartBurnout.hh
- source/game/kart/KartMove.cc
- source/game/kart/KartMove.hh
- source/game/kart/KartState.cc
- source/game/kart/KartState.hh
This synchronizes burnout physics when holding acceleration for too long during race countdown. Verified sync if attempting to activate an item during burnout. Verified analog stick inputs are still respected during burnout.
> Implement start boost burnout

- configure.py
- source/egg/core/Heap.cc
- source/egg/math/Math.cc
- source/game/field/ObjectCollisionBase.cc
- source/game/kart/KartHalfPipe.cc
We never use doubles (except for paired singles), and implicit float promotion has only ever caused sync issues that become very difficult to track down. Just like with adding `nodiscard` to our functions, we should merge these changes in order to limit the types of mistakes that can be introduced during future development.
**NOTE:** C++ standard says variadic functions must always promote floats to doubles, so unfortunately this means any use of `printf` with `%f` will require a `static_cast<f64>` in order to compile. I completely predict that new developers will run into this, so I'm not sure what can be done to make this less of a pain.
> Error on implicit float-to-double promotion

- source/game/system/ResourceManager.cc
renames the folder where assets are stored from `Kinoko` to `Race`, matching the naming convention of mario kart wii. 
this also helps contributors on MacOS (e.g. me) who can't have two directories/files with the same name (case insensitve) in the same directory. i also mentioned that [here](https://github.com/vabold/Kinoko/issues/14#issuecomment-2161405120) under issue #14 
the github action's runtime file will also have to be updated accordingly.
> Rename asset folder

- source/game/kart/KartMove.cc
- source/game/kart/KartMove.hh
- source/game/kart/KartPhysics.cc
- source/game/kart/KartPhysics.hh
- source/game/kart/KartState.cc
- source/game/kart/KartState.hh
This is required for 0.1 target because approximately 7000 of the 95000 LC records in CTGP database desync because of auto transmission.
> Implement auto drifting

- source/game/kart/KartMove.cc
- source/game/kart/KartState.cc
- source/game/kart/KartState.hh
Also re-order the KartState functions to match the member ordering in-game.
> Fix SSMT canceling

- source/game/kart/KartObject.cc
`i` increments unconditionally, whereas `wheelIdx` only increments if we are not on the Blue Falcon's 0th tire idx.
> Fix bug related to tire allocation

- source/game/field/ObjectCollisionConvexHull.cc
- source/game/field/ObjectCollisionCylinder.cc
Also fix incorrect multiplication with ObjectCollisionCylinder that could shoot us in the foot later.
> Use paired singles for object collision transformation

- source/egg/math/Vector.cc
- source/egg/math/Vector.hh
- source/game/field/KColData.cc
I'm not immediately sure how to double-check for other uses elsewhere, but I think this is the only one we have to worry about?
> Fix inaccurate paired singles instructions

- source/game/field/KColData.cc
- source/game/field/KColData.hh
Since spans are non-owning, we need to ensure their data is deleted
> Delete spans on destruction in KColData

- source/game/field/ObjectDirector.cc
- source/game/field/obj/ObjectId.hh
- source/game/field/obj/ObjectParasolR.cc
- source/game/field/obj/ObjectParasolR.hh
- source/game/field/obj/ObjectRegistry.hh
This syncs the rSGB umbrella collision. `loadFlags` override is not required to sync, but figured I would add it anyway.
> Implement ParasolR (rSGB umbrellas)

- source/game/field/ObjectDirector.cc
- source/game/field/obj/ObjectId.hh
Coconut Mall's `PalmTree` is just a `ObjectCollidable`
> Implement PalmTree (CM trees)

- source/game/item/ItemDirector.cc
- source/game/item/ItemDirector.hh
- source/game/item/ItemInventory.cc
- source/game/item/ItemInventory.hh
- source/game/item/KartItem.cc
- source/game/item/KartItem.hh
- source/game/kart/KartMove.cc
This was an outstanding desync possible on Luigi Circuit, if you press the "item" button after respawning. Kinoko did not yet remove your items from your inventory. In-game nothing would happen if you press the "item" button, but in Kinoko it would still activate a shroom boost.
This fixes #148
> Clear item inventory when respawning

- source/game/system/CourseMap.cc
> Use ternaries for CourseMap constructor returns

- source/egg/util/Stream.cc
- source/egg/util/Stream.hh
- source/game/field/KColData.cc
- source/game/field/ObjectHitTable.cc
- source/game/kart/KartParamFileManager.cc
- source/game/system/KPadController.cc
- source/game/system/map/MapdataCannonPoint.cc
- source/game/system/map/MapdataCheckPath.cc
- source/game/system/map/MapdataCheckPoint.cc
- source/game/system/map/MapdataGeoObj.cc
- source/game/system/map/MapdataJugemPoint.cc
- source/game/system/map/MapdataStageInfo.cc
- source/game/system/map/MapdataStartPoint.cc
This fixes #228 and fixes #198
> Refine Stream state checks and clean up RamStream ctor usage

- source/egg/math/BoundBox.cc
- source/egg/math/Matrix.cc
- source/egg/math/Matrix.hh
- source/egg/math/Quat.cc
- source/egg/math/Quat.hh
- source/egg/math/Vector.cc
- source/egg/math/Vector.hh
- source/game/field/ObjectCollisionBase.cc
- source/game/kart/CollisionGroup.cc
- source/game/kart/KartCollide.cc
- source/game/kart/KartDynamics.cc
- source/game/kart/KartReject.cc
- source/game/kart/KartState.cc
- source/game/kart/KartSub.cc
This should help with performance. Thank you to ficool2 for the `std::numeric_limits<f32>::signaling_NaN()` suggestion. I also moved the Quatf non-default constructors to the header, since it's assuredly a performance improvement as well.
NOTE: BoundBox2f does not need `ifdef` because each `Vector3f` member will have the proper default constructor implementation as a result of their `ifdef`'s.
> Remove initialization in default constructors

- source/egg/math/Quat.cc
- source/egg/math/Quat.hh
- source/egg/math/Vector.cc
- source/egg/math/Vector.hh
- source/game/field/ObjectCollisionBase.cc
- source/game/kart/KartCollide.cc
- source/game/kart/KartDynamics.cc
- source/game/kart/KartJump.cc
- source/game/kart/KartMove.cc
When the dot product is less than epsilon, we expect to return 0.0f. Also renaming `dot()` to `squareLength` to better represent the significance of what this function is used for.
> Fix incorrect vector normalisation with dot products smaller than epsilon

- source/egg/math/Matrix.cc
- source/egg/math/Matrix.hh
- source/game/field/ObjectCollisionSphere.cc
- source/game/field/ObjectCollisionSphere.hh
- source/game/field/ObjectDirector.cc
- source/game/field/obj/ObjectDokan.cc
- source/game/field/obj/ObjectDokan.hh
- source/game/field/obj/ObjectId.hh
- source/game/field/obj/ObjectPuchiPakkun.hh
- source/game/field/obj/ObjectRegistry.hh
- source/game/kart/KartMove.cc
- Piranhas are really pipes (ObjectDokan) because they fly upwards if you hit them, but they have specialized behavior in calcCollisionTransform.
- Added as a typedef to help with readability
- Also had to add to ObjectCollisionSphere
> Implement ObjectPuchiPakkun (rMR piranhas)

- include/Common.hh
- include/ScopeLock.hh
- source/abstract/memory/ExpHeap.cc
- source/abstract/memory/ExpHeap.hh
- source/egg/core/ExpHeap.cc
- source/egg/core/ExpHeap.hh
- source/game/field/ObjectCollisionKart.cc
- source/game/field/ObjectDirector.cc
- source/game/field/ObjectDirector.hh
- source/game/field/ObjectHitTable.cc
- source/game/field/obj/ObjectCollidable.cc
- source/game/field/obj/ObjectNoImpl.cc
- source/game/field/obj/ObjectNoImpl.hh
- source/game/kart/KartMove.cc
- source/game/kart/KartObject.cc
- source/game/scene/GameScene.cc
- source/game/scene/GameScene.hh
- source/game/scene/RaceScene.cc
- source/game/scene/RootScene.cc
- source/game/scene/RootScene.hh
- source/game/system/CourseMap.cc
- source/game/system/map/MapdataPointInfo.cc
- source/game/system/map/MapdataPointInfo.hh
- source/host/KTestSystem.cc
- source/host/KTestSystem.hh
The GameScene still leaks due to being handled by the Disposer - fixing this problem will require a library change at a later point.
> Add memory profiling and fix memory leaks

- source/game/field/CollisionDirector.cc
- source/game/field/CollisionDirector.hh
- source/game/field/CourseColMgr.cc
- source/game/field/CourseColMgr.hh
- source/game/field/KColData.cc
- source/game/field/KColData.hh
- source/game/kart/KartCollide.cc
These will be required for ObjectDrivable and (mainly) ObjectKCL. Function signatures are standardized across all collision check funcs (some had float arg out-of-order, some had different variable names). Just like with spheres, I combined the two main collision check functions since they differ only by a few instructions.
> Add missing collision functions and clean up

- source/game/field/BoxColManager.cc
- source/game/field/BoxColManager.hh
- source/game/field/CollisionDirector.cc
- source/game/field/CollisionDirector.hh
- source/game/field/CourseColMgr.cc
- source/game/field/CourseColMgr.hh
- source/game/field/KColData.cc
- source/game/field/KColData.hh
- source/game/field/obj/ObjectBase.hh
- source/game/field/obj/ObjectCollidable.hh
- source/game/field/obj/ObjectDokan.cc
- source/game/field/obj/ObjectDrivable.cc
- source/game/field/obj/ObjectDrivable.hh
- source/game/field/obj/ObjectNoImpl.hh
- source/game/kart/KartCollide.cc
- source/game/kart/KartCollide.hh
- source/game/kart/KartHalfPipe.cc
- source/game/kart/KartMove.cc
- source/game/kart/KartMove.hh
- source/game/kart/KartReject.cc
Adds the abstract class ObjectDrivable which is the base of objects such as BCwii's "TwistedWay" and RR's "Aurora" wavy road.
`ObjectDrivable::initCollision` is nop for now, but I wanted to add it pre-emptively since ObjectKCL will need to override it anyway. Less diff noise for that PR if I just add it now.
> Implement ObjectDrivable

- source/game/kart/KartReject.cc
Independently ran into this issue separately from John's PR https://github.com/vabold/Kinoko/pull/264
Short-circuiting prevented some calls to `calcRejection`.
**NOTE**: This will affect `STATUS.md` for #271 as follows:
```
rr-rta-1-24-751         3194    ->      5491    [LABEL]
rr-ng-rta-2-24-281      1207    ->      2217    [LATER]
```
> Unconditionally call calcRejection

- source/game/kart/KartDynamics.cc
This causes desyncs when leaving the RR cannon.
> Add missing terminal velocity check

- STATUS.md
- source/game/kart/CollisionGroup.cc
- source/game/kart/CollisionGroup.hh
- source/game/kart/KartCollide.cc
- source/game/kart/KartMove.cc
- source/game/kart/KartReject.cc
- source/game/kart/KartState.cc
- source/game/kart/KartState.hh
After ObjectAurora, this will sync the RR NG WR. This can cause a desync when interacting with the invisible wall above a zipper along reject road.
> Add missing invisible wall checks

- .github/workflows/build.yml
Tested with my fork
https://github.com/malleoz/Kinoko/pull/2
The `push` action only appears in the list because this action exists in the same repo as the PR. This shows that we check out the correct commit to check against formatting.
> Fix formatting action for Pull Request branches

- source/egg/math/Vector.cc
- source/egg/math/Vector.hh
- source/game/field/Rail.cc
- source/game/field/Rail.hh
- source/game/field/RailInterpolator.cc
- source/game/field/RailInterpolator.hh
- source/game/field/RailManager.cc
- source/game/field/RailManager.hh
- source/game/field/obj/ObjectBase.cc
- source/game/field/obj/ObjectBase.hh
- source/game/system/map/MapdataGeoObj.hh
- source/game/system/map/MapdataPointInfo.cc
- source/game/system/map/MapdataPointInfo.hh
This PR implements the following:
- Rail
- RailLine
- RailSpline
- RailInterpolator
- RailLinearInterpolator
- RailSmoothInterpolator
- RailManager
It's a bit tricky to trim this down more unfortunately, because Rails depend on Interpolators which depend on RailManager which depend on Rails.
Validated rails via `PenguinM` and `Kuribo`. These are the walking-only penguins and Goombas. They make use of linear and smooth interpolators. Goombas oscillate while penguins have continuous/looping rail points. This should cover enough bases. I was going to try to validate the speed change behavior that can occur for sliding penguins, for example, but sliding penguins' state has a dependency on drawMdl. For right now, I think this is sufficient testing.
> Implement Rail, RailInterpolator, and RailManager

- source/egg/math/Matrix.cc
- source/egg/math/Matrix.hh
- source/game/field/CourseColMgr.hh
- source/game/field/KColData.cc
- source/game/field/KColData.hh
- source/game/field/ObjColMgr.cc
- source/game/field/ObjColMgr.hh
This is a prerequisite for `ObjectKCL`, since each `ObjectKCL` holds its own `ObjColMgr` member in order to perform collision checks.
> Add ObjColMgr

- source/game/field/ObjectDirector.cc
- source/game/field/obj/ObjectId.hh
The trees on rDS are primitive `ObjectCollidable`s. They end up being constructed at `0x8082690C`.
> Add TownTreeDSc

- source/game/scene/RaceScene.cc
We forgot to initialize the RailManager. No objects are currently implementing `loadRails` so no accesses to the manager were actually being performed yet.
> Add creation and destruction of RailManager singleton

- source/game/field/obj/ObjectBase.cc
- source/game/field/obj/ObjectBase.hh
- source/game/field/obj/ObjectCollidable.cc
- source/game/render/AnmMgr.cc
- source/game/render/AnmMgr.hh
- source/game/render/DrawMdl.cc
- source/game/render/DrawMdl.hh
In `ObjectBase::loadGraphics` I skipped the use of `0x8055BA00` since it ends up causing a duplicate call to `getFile` which seemed unnecessary and taxing.
`playAnim` is required because when we query for a Goomba's animation framecount, it does so by querying into the active Chr animation.
> Implement REL wrapper for AnmObjChrRes

- source/egg/core/Heap.cc
- source/game/field/ObjectDrivableDirector.cc
- source/game/field/RailManager.cc
Previously, deleting nullptr would be no-op because nullptr would not be found in a containing heap. Rather than search through all of the heaps just to end up not finding anything, we simply return immediately.
> Fix memory leaks and improve deleting nullptr

- source/game/kart/KartHalfPipe.cc
This could cause a desync on GCN Waluigi Stadium if you hit a firebar with enough speed such that you touch the zipper in the half-pipe section.
> Add missing KartAction check for zippers

- source/egg/core/SceneManager.cc
This will fix an eventual memory leak when decoupling the memory allocator.
Closes #266.
> Correctly delete the scene in SceneManager

- source/game/kart/KartCollide.cc
- source/game/kart/KartMove.cc
- source/game/kart/KartState.cc
- source/game/kart/KartState.hh
This affects whether `mainRot` or `fullRot` is used in `KartCollide::findCollision()`.
> Implement KartState flag for spinout actions

- source/game/kart/KartMove.cc
This, in conjunction with #314, syncs all rWS ghosts on the CTGP database.
> Add missing action check for boost panels and ramps

- source/egg/math/Math.hh
This will be needed for `GetAnmResult` in a later PR to properly compute player scaling when getting unsquished from Moonview Highway cars.
> Add Geotale's fres implementation

- source/game/kart/KartHalfPipe.cc
`state()->isInAction()` and `StopHalfPipeState` checks happen in a separate block than `m_touchingZipper && state()->isAirStart()`.
> Fix branching in KartHalfPipe::calc

- source/game/field/ObjectFlowTable.cc
- source/game/field/ObjectFlowTable.hh
- source/game/field/obj/ObjectBase.cc
- source/game/field/obj/ObjectBase.hh
- source/game/field/obj/ObjectCollidable.cc
- source/game/field/obj/ObjectCollidable.hh
- source/game/field/obj/ObjectId.hh
This PR adds the overloaded `ObjectBase` and `ObjectCollidable` constructors which take in a name, pos, rot, and scale rather than the typical params.
> Add name-based Object constructors

- source/game/kart/KartMove.cc
- source/game/kart/KartMove.hh
- source/game/kart/KartObjectManager.cc
- source/game/kart/KartObjectManager.hh
- source/game/kart/KartObjectProxy.cc
- source/game/kart/KartObjectProxy.hh
- source/game/kart/KartScale.cc
- source/game/kart/KartScale.hh
This class is used to compute changes in the kart's scale due to hitting TF stompers or MH cars. There is initially a scaling down to `{1.0f, 0.3f, 1.0f}` followed by an eventual unsquash animation. These functions won't effectively do anything until some more code is added in a future PR.
> Implement KartScale

- source/egg/core/BitFlag.hh
- source/game/kart/KartMove.cc
This adds some more functions to `TBitFlag` to support some other common bit checks. We don't need these immediately, but we will need them for `TBitFlagExt` when we turn `KartState`'s bitfields into `TBitFlagExt`. So I want to add these functions to both class types.
> Add more bit check functions to TBitFlag

- STATUS.md
- source/game/field/ObjectDirector.cc
- source/game/field/obj/ObjectAmi.cc
- source/game/field/obj/ObjectAmi.hh
- source/game/field/obj/ObjectId.hh
- source/game/field/obj/ObjectRegistry.hh
- source/game/field/obj/ObjectTuribashi.cc
This syncs the Maple Treeway net.
- The net works by combining a spatial sin wave and a temporal sin wave. If you are on the z-axis edge of the net, the bounce effect is dampened compared to when you are in the center. The temporal sin wave has a period of 70 frames for which the net moves up-and-down.
- For Turibashi, I noticed the same flag check ordering improvement, so I applied it here as well.
> Sync ObjectAmi (Maple Treeway net)

- source/game/field/ObjectDirector.cc
- source/game/field/obj/ObjectBase.hh
- source/game/field/obj/ObjectId.hh
- source/game/field/obj/ObjectItemboxLine.cc
- source/game/field/obj/ObjectItemboxLine.hh
- source/game/field/obj/ObjectItemboxPress.cc
- source/game/field/obj/ObjectItemboxPress.hh
- source/game/field/obj/ObjectPress.cc
- source/game/field/obj/ObjectPress.hh
- source/game/field/obj/ObjectRegistry.hh
These are the left/right side stompers on Toad's Factory. They're managed by ObjectItemboxLine and ObjectItemboxPress since the stompers interact with itemboxes in GP mode. We omit a lot of implementation since we only care about the stompers themselves.
> Implement ObjectPressSenko

- source/game/field/CollisionDirector.cc
- source/game/field/CollisionDirector.hh
- source/game/field/KCollisionTypes.hh
- source/game/field/obj/ObjectBelt.cc
- source/game/kart/KartCollide.cc
- source/game/kart/KartReject.cc
From: https://vabold.github.io/Kinoko/docs/html/todo.html
Member [Field::CollisionDirector::setCurrentCollisionTrickable]
Member [Field::CollisionDirector::setCurrentCollisionVariant]
Attributes should be represented as a bitfield. We can use a union. We will accomplish this in a future PR.
Changes:
- Created eCollisionAttribute enum class, which allows all 16 attribute bits to be directly accessible through the attribute var, while allowing individual bit access
- Added helpers to get multi bit members
- Removed KCL_VARIANT_TYPE and KCL_ATTRIBUTE_TYPE macros where possible for clarity
Notes:
Did not modify attribute that is part of CourseColMgr.cc. Updating this attribute would require edits to https://github.com/jacobop2/Kinoko/blob/main/source/game/field/CourseColMgr.hh#L19, which …
> Collision entry attribute bitfield

- source/game/field/StateManager.hh
- source/game/field/obj/ObjectCarTGE.cc
- source/game/field/obj/ObjectCarTGE.hh
- source/game/field/obj/ObjectChoropu.cc
- source/game/field/obj/ObjectChoropu.hh
- source/game/field/obj/ObjectCow.cc
- source/game/field/obj/ObjectCow.hh
- source/game/field/obj/ObjectKuribo.cc
- source/game/field/obj/ObjectKuribo.hh
I've simplified the StateManager infrastructure we use to remove the need for the middleman templated class. Now, the m_entryIds and m_entries can be created entirely in the base templated class's constructor.
It is now the responsibility of the object class, rather than the middleman class, to own a STATE_ENTRIES std::array of StateManagerEntry<T>.
I've also moved commonly re-used state calc logic into its own calc() function within StateManager.
> Rework StateManager
